# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: 079ae508
    url: /#bio
    weight: 10
  - name: Working Papers
    identifier: latest-work
    url: /#latest
    weight: 20
  - name: Publications
    identifier: 33d34628
    url: /#journal-publications
    weight: 30
  - name: Contact
    identifier: 58f09f2d
    url: /#contact
    weight: 50
