hugoblox:
  schema: "2.0"
  identity:
    name: James Cloyne
    type: person
    tagline: Professor of Economics | UC Davis
    description: James Cloyne is a Professor of Economics at the University of California Davis.
  icon:
    pack: fas
    name: circle-dot
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: "neutral"
  typography:
    font: sans
    size: md
  layout:
    radius: sm
    spacing: compact
    avatar_shape: circle
  header:
    enable: true
    style: navbar-simple
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
